/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#2d3133",
        "on-surface": "#e0e3e5",
        "on-error": "#690005",
        "agri": "#facc15",
        "on-surface-variant": "#c6c6cd",
        "on-secondary-fixed-variant": "#3a485c",
        "intelligence-blue": "#0f172a",
        "mining": "#a855f7",
        "primary-container": "#0f172a",
        "secondary-fixed": "#d5e3fd",
        "tertiary": "#b9c8de",
        "surface": "#101415",
        "outline": "#909097",
        "background": "#101415",
        "surface-dim": "#101415",
        "secondary": "#b9c7e0",
        "on-primary-fixed": "#131b2e",
        "secondary-container": "#3c4a5e",
        "surface-tint": "#bec6e0",
        "tertiary-fixed-dim": "#b9c8de",
        "gas-flare": "#f59e0b",
        "on-primary-container": "#798098",
        "surface-bright": "#363a3b",
        "on-background": "#e0e3e5",
        "on-tertiary-fixed-variant": "#39485a",
        "other-status": "#64748b",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#565e74",
        "inverse-surface": "#e0e3e5",
        "shell-slate": "#1e293b",
        "on-primary": "#283044",
        "error-container": "#93000a",
        "on-tertiary": "#233143",
        "secondary-fixed-dim": "#b9c7e0",
        "primary-fixed-dim": "#bec6e0",
        "outline-variant": "#45464d",
        "on-secondary-fixed": "#0d1c2f",
        "primary": "#bec6e0",
        "on-secondary": "#233144",
        "surface-variant": "#323537",
        "surface-container-lowest": "#0b0f10",
        "tertiary-fixed": "#d4e4fa",
        "on-tertiary-fixed": "#0d1c2d",
        "surface-container": "#1d2022",
        "wildfire": "#fbbf24",
        "tertiary-container": "#081828",
        "industrial-fire": "#ef4444",
        "surface-container-high": "#272a2c",
        "primary-fixed": "#dae2fd",
        "on-secondary-container": "#abb9d2",
        "surface-container-low": "#191c1e",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container-highest": "#323537",
        "on-tertiary-container": "#738296"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "gutter": "16px",
        "margin-mobile": "16px",
        "xs": "4px",
        "margin-desktop": "32px",
        "sm": "8px",
        "xl": "32px",
        "lg": "24px",
        "md": "16px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "metadata-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "status-pill": ["Inter", "sans-serif"],
        "kpi-value": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "900" }],
        "metadata-sm": ["12px", { lineHeight: "1.5", letterSpacing: "0.02em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "status-pill": ["11px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "kpi-value": ["24px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "900" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "900" }]
      },
      animation: {
        "spin-slow": "spin-slow 4s linear infinite",
      },
      keyframes: {
        "spin-slow": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" }
        }
      }
    },
  },
  plugins: [],
}
